Product.create(name: "Iphone", price: 1000, quantity: 1)
Product.create(name: "Samsung", price: 1000, quantity: 2)
Product.create(name: "Apple watch", price: 500, quantity: 3)
Product.create(name: "Macbook", price: 2000, quantity: 4)
Product.create(name: "Ipad", price: 800, quantity: 5)

Category.create(name: "Phones", description: "phones", status: true)
Category.create(name: "Laptops", description: "laptops", status: true)
Category.create(name: "Tablets", description: "tablets", status: true)
Category.create(name: "Watches", description: "watches", status: true)
Category.create(name: "Accessories", description: "accessories", status: true)
